import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDownRight, ArrowUpRight, BarChart3, Check, ChevronDown, Clock3, Copy, Download, Gauge, Link2, Mail, MousePointer2, ScanLine, Share2, Sparkles, TrendingUp, Users, X, Zap } from "lucide-react";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import OperationsShell from "../components/OperationsShell";

const series = { Today: [42, 55, 47, 61, 74, 69, 86, 78, 91, 87, 96, 101], "7 days": [64, 71, 69, 84, 78, 91, 88, 102, 97, 110, 106, 122], "30 days": [52, 66, 61, 73, 82, 79, 95, 91, 108, 112, 118, 134] };
type Range = keyof typeof series | "Custom";
const workers = [{ name: "Mei Lin", id: "047", orders: "18", accuracy: "99.2%", time: "05:48", state: "Active" }, { name: "Rizky Adi", id: "031", orders: "16", accuracy: "98.4%", time: "06:12", state: "Review" }, { name: "Chen Wei", id: "052", orders: "14", accuracy: "98.9%", time: "06:36", state: "Active" }, { name: "Siti Rahma", id: "019", orders: "11", accuracy: "97.8%", time: "07:04", state: "Offline" }];
const prefKey = "snapar-picker.analytics-preferences";

export default function Analytics() {
  const [range, setRange] = useState<Range>("Today");
  const [metric, setMetric] = useState("Orders cleared");
  const [exporting, setExporting] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [customOpen, setCustomOpen] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [startDate, setStartDate] = useState("2026-09-01");
  const [endDate, setEndDate] = useState("2026-09-09");
  const [notice, setNotice] = useState("");
  const chartRef = useRef<HTMLDivElement>(null);
  const values = useMemo(() => range === "Custom" ? series["30 days"] : series[range], [range]);
  const max = Math.max(...values);
  const rangeLabel = range === "Custom" ? `${startDate} → ${endDate}` : range;

  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem(prefKey) || "null");
      if (saved) { setRange(saved.range || "Today"); setMetric(saved.metric || "Orders cleared"); setStartDate(saved.startDate || "2026-09-01"); setEndDate(saved.endDate || "2026-09-09"); }
    } catch { /* use defaults when storage is unavailable */ }
  }, []);
  useEffect(() => {
    localStorage.setItem(prefKey, JSON.stringify({ range, metric, startDate, endDate }));
  }, [range, metric, startDate, endDate]);

  function flash(message: string) { setNotice(message); window.setTimeout(() => setNotice(""), 2400); }
  function applyCustomRange() {
    if (!startDate || !endDate || startDate > endDate) { flash("Choose a valid start and end date"); return; }
    setRange("Custom"); setCustomOpen(false); flash(`Custom range applied: ${startDate} → ${endDate}`);
  }
  function summaryText() { return `SnapAR Picker analytics report\nPeriod: ${rangeLabel}\nMetric: ${metric}\nOrders cleared: 1,284 (+18.4%)\nPick accuracy: 98.7% (+4.2%)\nAverage pick time: 06:42 (-18%)\nTop worker: Mei Lin · 18 orders · 99.2% accuracy\nEdge insight: Search time reduced 31%.`; }
  function reportLink() { return `${window.location.origin}/analytics?report=performance&range=${encodeURIComponent(rangeLabel)}&metric=${encodeURIComponent(metric)}`; }
  async function shareNative() {
    setSharing(true);
    try { if (navigator.share) { await navigator.share({ title: "SnapAR Picker analytics", text: summaryText(), url: reportLink() }); flash("Native share sheet opened"); } else { await navigator.clipboard.writeText(reportLink()); flash("Share link copied — native sharing is unavailable"); } }
    catch { flash("Share was cancelled"); }
    finally { setSharing(false); setShareOpen(false); }
  }
  async function copyLink() { await navigator.clipboard.writeText(reportLink()); setShareOpen(false); flash("Native shareable link copied"); }
  function emailReport() { window.location.href = `mailto:?subject=${encodeURIComponent(`SnapAR Picker report · ${rangeLabel}`)}&body=${encodeURIComponent(summaryText())}`; setShareOpen(false); flash("Opening your email client"); }

  async function exportReport() {
    setExporting(true);
    try {
      const pdf = new jsPDF({ unit: "pt", format: "a4" });
      const width = pdf.internal.pageSize.getWidth(); const height = pdf.internal.pageSize.getHeight();
      const lime: [number, number, number] = [186, 255, 86]; const ink: [number, number, number] = [14, 17, 12]; const muted: [number, number, number] = [132, 145, 119]; const light: [number, number, number] = [237, 242, 224];
      const footer = (page: number) => { pdf.setDrawColor(63, 76, 51); pdf.line(42, height - 55, width - 42, height - 55); pdf.setTextColor(...lime); pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); pdf.text("SNAPAR PICKER", 42, height - 35); pdf.setTextColor(...muted); pdf.setFont("helvetica", "normal"); pdf.text("Confidential · Edge operations telemetry", width - 240, height - 35); pdf.setTextColor(80, 95, 69); pdf.text(`PAGE 0${page}`, width - 70, height - 20); };
      const background = () => { pdf.setFillColor(...ink); pdf.rect(0, 0, width, height, "F"); pdf.setFillColor(...lime); pdf.rect(0, 0, width, 7, "F"); };
      background(); pdf.setTextColor(...lime); pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); pdf.text("SNAPAR PICKER", 42, 47); pdf.setTextColor(...muted); pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); pdf.text("EDGE OPERATIONS / PERFORMANCE SIGNALS", 42, 64); pdf.setTextColor(...light); pdf.setFont("helvetica", "bold"); pdf.setFontSize(27); pdf.text("Operational intelligence report", 42, 104); pdf.setTextColor(...muted); pdf.setFontSize(10); pdf.text(`Reporting period: ${rangeLabel}    •    Active metric: ${metric}`, 42, 128); pdf.setDrawColor(63, 76, 51); pdf.line(42, 149, width - 42, 149);
      pdf.setTextColor(...lime); pdf.setFontSize(10); pdf.text("01 / KPI SUMMARY", 42, 194); pdf.setTextColor(...light); pdf.setFontSize(21); pdf.text("A sharper shift, at a glance.", 42, 228); const cards = [["ORDERS CLEARED", "1,284", "18.4% vs previous period"], ["PICK ACCURACY", "98.7%", "4.2% vs manual baseline"], ["AVG. PICK TIME", "06:42", "18% faster this shift"]]; cards.forEach(([label, value, detail], index) => { const x = 42 + (index % 2) * 245; const y = 280 + Math.floor(index / 2) * 112; pdf.setFillColor(26, 33, 21); pdf.roundedRect(x, y, 215, 84, 5, 5, "F"); pdf.setTextColor(...muted); pdf.setFontSize(8); pdf.text(label, x + 15, y + 22); pdf.setTextColor(...lime); pdf.setFont("helvetica", "bold"); pdf.setFontSize(23); pdf.text(value, x + 15, y + 52); pdf.setTextColor(172, 215, 121); pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); pdf.text(detail, x + 15, y + 68); }); pdf.setTextColor(...muted); pdf.setFontSize(9); pdf.text("Operational note", 42, 535); pdf.setTextColor(...light); pdf.setFontSize(13); pdf.text("Spatial guidance is doing the heavy lifting.", 42, 560); pdf.setTextColor(...muted); pdf.setFontSize(9); pdf.text("Search time reduced -31%  •  Verification confidence +12.8%  •  Offline minutes 42", 42, 582); footer(1);
      pdf.addPage(); background(); pdf.setTextColor(...lime); pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); pdf.text("SNAPAR PICKER", 42, 47); pdf.setTextColor(...light); pdf.setFontSize(21); pdf.text("02 / CHARTS", 42, 98); pdf.setTextColor(...muted); pdf.setFont("helvetica", "normal"); pdf.setFontSize(10); pdf.text(`${metric} · ${rangeLabel}`, 42, 121); if (chartRef.current) { const canvas = await html2canvas(chartRef.current, { backgroundColor: "#131611", scale: 2, logging: false }); pdf.addImage(canvas.toDataURL("image/png"), "PNG", 42, 152, width - 84, 265, undefined, "FAST"); } pdf.setTextColor(...light); pdf.setFont("helvetica", "bold"); pdf.setFontSize(15); pdf.text("How to read this signal", 42, 477); pdf.setTextColor(...muted); pdf.setFont("helvetica", "normal"); pdf.setFontSize(10); pdf.text("Bars show throughput over the selected period. The lime signal represents", 42, 503); pdf.text("work completed with edge assistance available at the physical task.", 42, 519); pdf.setTextColor(...lime); pdf.setFontSize(12); pdf.text("4.2ms", 42, 571); pdf.setTextColor(...muted); pdf.setFontSize(9); pdf.text("median local inference latency", 92, 571); pdf.setTextColor(...lime); pdf.setFontSize(12); pdf.text("98.4%", 42, 603); pdf.setTextColor(...muted); pdf.setFontSize(9); pdf.text("scene recognition confidence", 92, 603); footer(2);
      pdf.addPage(); background(); pdf.setTextColor(...lime); pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); pdf.text("SNAPAR PICKER", 42, 47); pdf.setTextColor(...light); pdf.setFontSize(21); pdf.text("03 / WORKER PERFORMANCE", 42, 98); pdf.setTextColor(...muted); pdf.setFont("helvetica", "normal"); pdf.setFontSize(10); pdf.text(`Live workforce pulse · ${rangeLabel}`, 42, 121); const cols = [42, 173, 277, 382, 475]; pdf.setFillColor(29, 38, 23); pdf.rect(42, 156, width - 84, 32, "F"); pdf.setTextColor(...muted); pdf.setFontSize(8); ["WORKER", "ORDERS", "ACCURACY", "AVG. TIME", "STATE"].forEach((label, index) => pdf.text(label, cols[index], 176)); workers.forEach((worker, index) => { const y = 220 + index * 58; pdf.setDrawColor(47, 58, 40); pdf.line(42, y + 18, width - 42, y + 18); pdf.setTextColor(...light); pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); pdf.text(`${worker.name} · ${worker.id}`, cols[0], y); pdf.setTextColor(...muted); pdf.setFont("helvetica", "normal"); pdf.text(worker.orders, cols[1], y); pdf.text(worker.accuracy, cols[2], y); pdf.text(worker.time, cols[3], y); pdf.setTextColor(worker.state === "Review" ? 224 : worker.state === "Offline" ? 150 : 186, worker.state === "Review" ? 184 : worker.state === "Offline" ? 165 : 255, worker.state === "Review" ? 117 : worker.state === "Offline" ? 145 : 86); pdf.text(worker.state.toUpperCase(), cols[4], y); }); pdf.setTextColor(...light); pdf.setFont("helvetica", "bold"); pdf.setFontSize(16); pdf.text("Team signal", 42, 515); pdf.setTextColor(...muted); pdf.setFont("helvetica", "normal"); pdf.setFontSize(10); pdf.text("Mei Lin is leading the shift with 18 completed orders and 99.2% accuracy.", 42, 540); pdf.text("One review state is active; one device is offline but sync is queued.", 42, 558); footer(3);
      pdf.save(`snapar-picker-${range === "Custom" ? `${startDate}-to-${endDate}` : String(range).toLowerCase().replace(/ /g, "-")}-report.pdf`); flash("Three-page PDF report downloaded");
    } catch { flash("PDF export could not capture the chart"); } finally { setExporting(false); }
  }

  return <OperationsShell eyebrow="PERFORMANCE SIGNALS">
    <section className="page-heading-row"><div><div className="kicker"><BarChart3 size={14} /> PERFORMANCE SIGNALS / EDGE TELEMETRY</div><h1>The operation<br /><em>gets sharper.</em></h1><p className="lede">See where spatial guidance compounds into faster, more accurate work — and where the system still needs attention.</p></div><div className="analytics-heading-actions"><div className="range-switch">{(Object.keys(series) as Array<keyof typeof series>).map((item) => <button className={range === item ? "selected" : ""} key={item} onClick={() => setRange(item)}>{item}</button>)}<button className={range === "Custom" ? "selected" : ""} onClick={() => setCustomOpen(true)}>Custom</button></div><div className="report-actions"><div className="share-menu-wrap"><button className="share-button" onClick={() => setShareOpen(!shareOpen)} disabled={sharing}><Share2 size={15} /> Share Report <ChevronDown size={13} /></button>{shareOpen && <div className="share-menu"><button onClick={shareNative}><Share2 size={14} /><span><strong>Native share</strong><small>Open device share sheet</small></span></button><button onClick={copyLink}><Copy size={14} /><span><strong>Copy shareable link</strong><small>Copy current report state</small></span></button><button onClick={emailReport}><Mail size={14} /><span><strong>Email summary</strong><small>Open your mail client</small></span></button></div>}</div><button className="export-button" onClick={exportReport} disabled={exporting}><Download size={15} /> {exporting ? "Preparing PDF..." : "Export PDF"}</button></div></div></section>
    {customOpen && <div className="custom-range-popover"><div className="custom-range-head"><div><span className="eyebrow">CUSTOM REPORT RANGE</span><strong>Select the period to analyze</strong></div><button onClick={() => setCustomOpen(false)}><X size={15} /></button></div><div className="date-fields"><label>START DATE<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><span>→</span><label>END DATE<input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label></div><div className="custom-range-foot"><small>Saved automatically for your next session.</small><button className="confirm-action" onClick={applyCustomRange}><Check size={14} /> Apply range</button></div></div>}
    <section className="analytics-kpis"><div className="analytics-card featured"><div className="analytics-card-top"><span>ORDERS CLEARED</span><TrendingUp size={17} /></div><strong>1,284</strong><p><ArrowUpRight size={13} /> 18.4% vs previous period</p><div className="spark-bars">{values.map((value, index) => <i style={{ height: `${(value / max) * 100}%` }} key={index} />)}</div></div><div className="analytics-card"><div className="analytics-card-top"><span>PICK ACCURACY</span><Gauge size={17} /></div><strong>98.7%</strong><p><ArrowUpRight size={13} /> 4.2% vs manual baseline</p><div className="ring-chart"><span>98<span>%</span></span></div></div><div className="analytics-card"><div className="analytics-card-top"><span>AVG. PICK TIME</span><Clock3 size={17} /></div><strong>06:42</strong><p><ArrowDownRight size={13} /> 18% faster this shift</p><div className="metric-sweep"><span style={{ width: "72%" }} /></div></div></section>
    <section className="analytics-grid"><div className="signal-chart" ref={chartRef}><div className="chart-head"><div><span className="eyebrow">THROUGHPUT / {rangeLabel.toUpperCase()}</span><h2>{metric}</h2></div><div className="metric-picker">{["Orders cleared", "AI inferences", "Accuracy"].map((item) => <button className={metric === item ? "selected" : ""} key={item} onClick={() => setMetric(item)}>{item}</button>)}</div></div><div className="chart-area"><div className="y-labels"><span>140</span><span>105</span><span>70</span><span>35</span><span>0</span></div><div className="bars-area">{values.map((value, index) => <div className="bar-column" key={index}><div className="bar" style={{ height: `${(value / 140) * 100}%` }}><span>{value}</span></div><small>{String(index + 1).padStart(2, "0")}</small></div>)}</div></div></div><div className="insight-panel"><div className="insight-heading"><Sparkles size={15} /><span>EDGE INSIGHT</span></div><h2>Spatial guidance is doing the heavy lifting.</h2><p>Workers using SnapAR are spending less time searching and more time confirming. The largest gain is in visually similar SKUs.</p><div className="insight-stat"><span>Search time reduced</span><strong>−31%</strong></div><div className="insight-stat"><span>Verification confidence</span><strong>+12.8%</strong></div><button className="ghost-action" onClick={() => setMetric("AI inferences")}><ScanLine size={15} /> Explore inference stream <MousePointer2 size={14} /></button></div></section>
    <section className="telemetry-strip"><div><Zap size={16} /><span>EDGE INFERENCES</span><strong>4,802</strong><small>this shift</small></div><div><ScanLine size={16} /><span>SCENES RECOGNIZED</span><strong>1,936</strong><small>98.4% confidence</small></div><div><Users size={16} /><span>WORKERS ACTIVE</span><strong>04</strong><small>one device syncing</small></div></section>
    {notice && <div className="analytics-notice"><Check size={15} /> {notice}</div>}
  </OperationsShell>;
}
