import { useMemo, useState } from "react";
import { ArrowUpRight, Box, Check, ChevronRight, Clock3, Filter, MapPin, PackageCheck, Search, SlidersHorizontal, TriangleAlert, X } from "lucide-react";
import OperationsShell from "../components/OperationsShell";

const orders = [
  { id: "#20481", customer: "Urban Market Co.", zone: "Hall C4", lines: 12, progress: 7, status: "Picking", priority: "Normal", eta: "08 min", tone: "live" },
  { id: "#20479", customer: "Nusa Retail Group", zone: "Hall D2", lines: 8, progress: 8, status: "Ready", priority: "High", eta: "03 min", tone: "ready" },
  { id: "#20476", customer: "Ming Trading", zone: "Hall A1", lines: 19, progress: 15, status: "Quality hold", priority: "Review", eta: "—", tone: "hold" },
  { id: "#20474", customer: "Pasar Baru Supply", zone: "Hall F7", lines: 24, progress: 24, status: "Complete", priority: "Normal", eta: "Done", tone: "done" },
  { id: "#20470", customer: "Lima Sourcing", zone: "Hall C4", lines: 6, progress: 2, status: "Queued", priority: "Normal", eta: "22 min", tone: "queued" },
];

export default function Orders() {
  const [filter, setFilter] = useState("All orders");
  const [selected, setSelected] = useState(orders[0]);
  const [query, setQuery] = useState("");
  const visible = useMemo(() => orders.filter((order) => (filter === "All orders" || order.status === filter) && `${order.id} ${order.customer}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  return <OperationsShell eyebrow="ORDER CONTROL">
    <section className="page-heading-row"><div><div className="kicker"><PackageCheck size={14} /> ORDER CONTROL / 24 ACTIVE</div><h1>Every pick,<br /><em>accounted for.</em></h1><p className="lede">A live queue that keeps operators, supervisors, and physical stock in the same loop.</p></div><button className="primary-action compact" onClick={() => setSelected(orders[0])}>Open active run <ArrowUpRight size={17} /></button></section>
    <section className="order-kpis"><div><span>ACTIVE ORDERS</span><strong>24</strong><small>+8 since 08:00</small></div><div><span>IN PICKING</span><strong>12</strong><small>87 lines in motion</small></div><div><span>QUALITY HOLDS</span><strong className="amber-text">03</strong><small>Need review</small></div><div><span>AVG. FULFILLMENT</span><strong>06:42</strong><small>−18% vs last shift</small></div></section>
    <section className="orders-layout"><div className="orders-main"><div className="table-toolbar"><div className="filter-tabs">{["All orders", "Picking", "Ready", "Quality hold", "Complete"].map((item) => <button className={filter === item ? "selected" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="search-box"><Search size={15} /><input placeholder="Search orders" value={query} onChange={(event) => setQuery(event.target.value)} /><SlidersHorizontal size={15} /></div></div><div className="orders-table"><div className="table-head"><span>ORDER / CUSTOMER</span><span>LOCATION</span><span>PROGRESS</span><span>STATUS</span><span>ETA</span></div>{visible.map((order) => <button className={`order-row ${selected.id === order.id ? "selected" : ""}`} key={order.id} onClick={() => setSelected(order)}><div className="order-id"><div className={`order-icon ${order.tone}`}><Box size={16} /></div><div><strong>{order.id}</strong><span>{order.customer}</span></div></div><span className="mono">{order.zone}</span><div className="progress-cell"><div className="mini-progress"><span style={{ width: `${(order.progress / order.lines) * 100}%` }} /></div><small>{order.progress}/{order.lines}</small></div><span className={`status-pill ${order.tone}`}>{order.status}</span><span className="mono eta">{order.eta}<ChevronRight size={14} /></span></button>)}</div></div><aside className="order-detail"><div className="detail-top"><span className="eyebrow">SELECTED ORDER</span><button onClick={() => setSelected(orders[0])}><X size={15} /></button></div><h2>{selected.id}</h2><p>{selected.customer}</p><div className="detail-status"><span className={`status-pill ${selected.tone}`}>{selected.status}</span><span className="mono">{selected.priority} priority</span></div><div className="detail-route"><div className="route-node"><MapPin size={15} /><div><span>Current node</span><strong>{selected.zone} / Worker 047</strong></div></div><div className="route-line-vertical" /><div className="route-node"><PackageCheck size={15} /><div><span>Destination</span><strong>Dispatch bay 02</strong></div></div></div><div className="detail-progress"><div><span>FULFILLMENT</span><strong>{selected.progress} <small>/ {selected.lines} lines</small></strong></div><div className="detail-bar"><span style={{ width: `${(selected.progress / selected.lines) * 100}%` }} /></div></div><div className="detail-actions"><button className="ghost-action" onClick={() => setSelected({ ...selected, status: "Quality hold", tone: "hold" })}><TriangleAlert size={15} /> Flag exception</button><button className="confirm-action" onClick={() => setSelected({ ...selected, status: "Complete", tone: "done", progress: selected.lines })}><Check size={15} /> Mark complete</button></div></aside></section>
  </OperationsShell>;
}
