import { useState } from "react";
import { BatteryCharging, CheckCircle2, ChevronRight, Glasses, Map, MapPin, MoreHorizontal, Radio, Signal, UserRound, Zap } from "lucide-react";
import OperationsShell from "../components/OperationsShell";

const workers = [
  { id: "047", name: "Mei Lin", area: "C4 / Beverage aisle", task: "Picking SKU-2048", progress: 58, battery: 82, state: "Active", color: "lime" },
  { id: "031", name: "Rizky Adi", area: "D2 / Fresh goods", task: "Quality inspection", progress: 74, battery: 64, state: "Review", color: "amber" },
  { id: "052", name: "Chen Wei", area: "A1 / Dry goods", task: "Navigating to rack", progress: 31, battery: 91, state: "Active", color: "lime" },
  { id: "019", name: "Siti Rahma", area: "F7 / Returns bay", task: "Offline sync", progress: 88, battery: 28, state: "Offline", color: "muted" },
];

export default function Workers() {
  const [selected, setSelected] = useState(workers[0]);
  const [focus, setFocus] = useState("All workers");
  const filtered = workers.filter((worker) => focus === "All workers" || worker.state === focus);
  return <OperationsShell eyebrow="WORKFORCE PULSE">
    <section className="page-heading-row"><div><div className="kicker"><Radio size={14} /> WORKFORCE PULSE / 04 CONNECTED</div><h1>See the shift<br /><em>in motion.</em></h1><p className="lede">Monitor the human layer of the warehouse without pulling people away from the physical task.</p></div><div className="live-counter"><span className="pulse-dot" /> 04 LIVE DEVICES <small>Last heartbeat 2s ago</small></div></section>
    <section className="worker-layout"><div className="worker-map"><div className="map-header"><div><span className="eyebrow">LIVE FLOOR PLAN</span><h2>Hall C4 / 06:42 local</h2></div><button onClick={() => setFocus("All workers")}><Map size={15} /> Recenter</button></div><div className="warehouse-map"><div className="map-grid" /><div className="aisle aisle-a">A1</div><div className="aisle aisle-b">B2</div><div className="aisle aisle-c">C4</div><div className="aisle aisle-d">D2</div>{workers.map((worker, index) => <button className={`worker-pip ${worker.color} ${selected.id === worker.id ? "selected" : ""}`} style={{ left: `${22 + index * 18}%`, top: `${29 + (index % 2) * 27}%` }} key={worker.id} onClick={() => setSelected(worker)}><span>{worker.id}</span></button>)}</div><div className="map-legend"><span><i className="legend-dot lime" /> Active</span><span><i className="legend-dot amber" /> Review</span><span><i className="legend-dot muted" /> Offline</span></div></div><div className="worker-list-panel"><div className="worker-filter">{["All workers", "Active", "Review", "Offline"].map((item) => <button className={focus === item ? "selected" : ""} key={item} onClick={() => setFocus(item)}>{item}</button>)}</div>{filtered.map((worker) => <button className={`worker-row ${selected.id === worker.id ? "selected" : ""}`} key={worker.id} onClick={() => setSelected(worker)}><div className={`worker-avatar ${worker.color}`}>{worker.name.split(" ").map((part) => part[0]).join("")}</div><div className="worker-copy"><strong>Worker {worker.id} · {worker.name}</strong><span>{worker.task}</span><small><MapPin size={11} /> {worker.area}</small></div><div className="worker-state"><span className={`status-pill ${worker.color === "lime" ? "live" : worker.color === "amber" ? "hold" : "queued"}`}>{worker.state}</span><ChevronRight size={14} /></div></button>)}</div></section>
    <section className="worker-detail"><div className="detail-identity"><div className="big-worker-avatar">{selected.name.split(" ").map((part) => part[0]).join("")}</div><div><span className="eyebrow">SELECTED WORKER</span><h2>Worker {selected.id} · {selected.name}</h2><p>{selected.area}</p></div><button className="detail-more"><MoreHorizontal size={18} /></button></div><div className="worker-stats"><div><Glasses size={16} /><span>DEVICE</span><strong>Connected</strong><small>AR1 Gen 1 · 120 fps</small></div><div><Zap size={16} /><span>EDGE AI</span><strong>Active</strong><small>4.2ms inference latency</small></div><div><BatteryCharging size={16} /><span>BATTERY</span><strong>{selected.battery}%</strong><small>Estimated 3h 42m</small></div><div><Signal size={16} /><span>ORDER PROGRESS</span><strong>{selected.progress}%</strong><small>Order #20481 · 7 / 12</small></div></div><button className="follow-worker" onClick={() => setSelected(selected)}>Follow {selected.name.split(" ")[0]}'s route <ChevronRight size={15} /></button></section>
  </OperationsShell>;
}
